const NUMBER_OF_STARTING_CARDS_IN_PLAYERS_HAND = 3;
const VISIBLE_CARDS = false;
const ALL_MOVES_LEGAL = true;
const DEBBUG_MODE = true;

module.exports = {
    NUMBER_OF_STARTING_CARDS_IN_PLAYERS_HAND,
    VISIBLE_CARDS,
    ALL_MOVES_LEGAL,
    DEBBUG_MODE
};
