// const NUMBER_OF_PLAYERS = 2;
const NUMBER_OF_STARTING_CARDS_IN_PLAYERS_HAND = 3;
const VISIBLE_CARDS = true;
const ALL_MOVES_LEGAL = true;


module.exports = {
    // NUMBER_OF_PLAYERS,
    NUMBER_OF_STARTING_CARDS_IN_PLAYERS_HAND,
    VISIBLE_CARDS,
    ALL_MOVES_LEGAL
};
